kubeConfig: ""
namespace: "k8s-node-perf-evaluation-services"
nodeSelector:
  labelSelector: ""
  fieldSelector: ""
testService:
  image: "ghcr.io/nadundesilva/tools/k8s-node-perf-evaluator/test-service:latest"
