kubeConfig: ""
namespace: "k8s-node-perf-evaluation-services"
testService:
  image: "ghcr.io/nadundesilva/tools/k8s-node-perf-evaluator/test-service:latest"
nodeSelector:
  labelSelector: ""
  fieldSelector: ""
ingress:
  className: ""
  tlsSecretName: ""
  hostnamePostfix: ""
  pathPrefix: "/"
  annotations: {}
