FROM golang:1.27.1@sha256:e0174e51e81218523251d85d248a90d24c3d5e81543b4f07a5d66229397db190 AS builder

ARG GIT_REVISION=""
ARG PROJECT_PKG=""
WORKDIR /repo

COPY ./ /repo/
RUN GIT_REVISION=${GIT_REVISION} PROJECT_PKG=${PROJECT_PKG} bash /repo/build-binary.sh test-runner

FROM alpine:3.24.2@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6

ARG USER_ID="10000"
ARG GROUP_ID="30000"

RUN addgroup -S \
        -g ${GROUP_ID} \
        k8s-node-perf-evaluator && \
    adduser -S \
        -u ${USER_ID} \
        -g ${GROUP_ID} \
        -s /bin/ash \
        test-runner

COPY --from=builder --chown=${USER_ID}:${GROUP_ID} /repo/out/test-runner /app/test-runner
WORKDIR /app

SHELL ["/bin/ash", "-c"]
USER ${USER_ID}:${GROUP_ID}

#checkov:skip=CKV_DOCKER_2: Not required since nothing is running
#trivy:ignore:AVD-DS-0026 # Not required since nothing is running
HEALTHCHECK NONE

ENTRYPOINT ["/app/test-runner"]
