FROM golang:1.25.1@sha256:d7098379b7da665ab25b99795465ec320b1ca9d4addb9f77409c4827dc904211 AS builder

ARG GIT_REVISION=""
ARG PROJECT_PKG=""
WORKDIR /repo

COPY ./ /repo/
RUN GIT_REVISION=${GIT_REVISION} PROJECT_PKG=${PROJECT_PKG} bash /repo/build-binary.sh test-runner

FROM alpine:3.22.1@sha256:4bcff63911fcb4448bd4fdacec207030997caf25e9bea4045fa6c8c44de311d1

ARG USER_ID="10000"
ARG GROUP_ID="30000"

RUN addgroup -S \
        -g ${GROUP_ID} \
        k8s-node-perf-evaluator && \
    adduser -S \
        -u ${USER_ID} \
        -g ${GROUP_ID} \
        -s /bin/ash \
        test-runner

COPY --from=builder --chown=${USER_ID}:${GROUP_ID} /repo/out/test-runner /app/test-runner
WORKDIR /app

SHELL ["/bin/ash", "-c"]
USER ${USER_ID}:${GROUP_ID}

#checkov:skip=CKV_DOCKER_2: Not required since nothing is running
#trivy:ignore:AVD-DS-0026 # Not required since nothing is running
HEALTHCHECK NONE

ENTRYPOINT ["/app/test-runner"]
