FROM golang:1.27.1@sha256:512690a5660563b57d37ecc31129e7f136e831db2aed24a1dbeb8ad7380dc0fa AS builder

ARG GIT_REVISION=""
ARG PROJECT_PKG=""
WORKDIR /repo

COPY ./ /repo/
RUN GIT_REVISION=${GIT_REVISION} PROJECT_PKG=${PROJECT_PKG} bash /repo/build-binary.sh test-service

FROM alpine:3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

# renovate: datasource=repology depName=alpine_3_22/curl versioning=deb
ARG CURL_VERSION="8.14.1-r2"

ARG USER_ID="10000"
ARG GROUP_ID="30000"

RUN apk update && \
    apk add --no-cache \
        curl="${CURL_VERSION}" && \
    rm -rf /var/cache/apk/* && \
    addgroup -S \
        -g ${GROUP_ID} \
        k8s-node-perf-evaluator && \
    adduser -S \
        -u ${USER_ID} \
        -g ${GROUP_ID} \
        -s /bin/ash \
        test-service

COPY --from=builder --chown=${USER_ID}:${GROUP_ID} /repo/out/test-service /app/test-service
WORKDIR /app

ENV SERVICE_PORT="8080"

SHELL ["/bin/ash", "-c"]
USER ${USER_ID}:${GROUP_ID}

EXPOSE 8080

HEALTHCHECK --start-period=10s \
    --retries=3 \
    --interval=10s \
    --timeout=10s \
    CMD curl -f "http://localhost:${SERVICE_PORT}/ping" || exit 1

ENTRYPOINT ["/app/test-service"]
