name: Build

on: [push, pull_request]

jobs:
  lint-code-base:
    name: Lint Code Base
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run GitHub Suprtlinter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_GO: false
      - name: Run GoLang CI Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

  build-tools:
    name: Build Perf Evaluator
    runs-on: ubuntu-20.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: ["test-service", "test-runner"]
    steps:
      - name: Login to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            GIT_REVISION=${{ github.sha }}
            PROJECT_PKG="github.com/${{ github.repository }}"
          file: docker/Dockerfile.${{ matrix.package }}
          push: true
          tags: ghcr.io/nadundesilva/tools/k8s-node-perf-evaluator/${{ matrix.package }}:latest
