name: Build

on: [push, pull_request]

permissions:
  contents: read
  packages: read

jobs:
  run-super-linter:
    name: Run GitHub Super Linter
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Lint Code Base
        uses: super-linter/super-linter@7bba2eeb89d01dc9bfd93c497477a57e72c83240 # v8.2.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_GITIGNORED_FILES: "true"
          VALIDATE_GO: "false"
          VALIDATE_PYTHON_BLACK: "false"
          VALIDATE_PYTHON_PYLINT: "false"

  codeql-analyze:
    name: CodeQL Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Initialize CodeQL
        uses: github/codeql-action/init@3599b3baa15b485a2e49ef411a7a4bb2452e7f93 # v3.30.5
        with:
          languages: go
      - name: Autobuild
        uses: github/codeql-action/autobuild@3599b3baa15b485a2e49ef411a7a4bb2452e7f93 # v3.30.5
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@3599b3baa15b485a2e49ef411a7a4bb2452e7f93 # v3.30.5

  test-docker-images:
    name: Test Docker Images
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.13.7"
      - name: Set up Docker
        uses: docker/setup-docker-action@b60f85385d03ac8acfca6d9996982511d8620a19 # v4.3.0
      - name: Setup pipx
        run: |
          sudo apt update
          sudo apt install pipx
          pipx ensurepath
      - name: Setup Poetry
        run: pipx install poetry
      - name: Install Test Dependencies
        run: poetry sync
      - name: Validate Types in Tests
        run: poetry run mypy .
      - name: Run Tests
        run: poetry run pytest

  build-tools:
    name: Build Perf Evaluator
    runs-on: ubuntu-latest
    needs:
      - run-super-linter
      - codeql-analyze
      - test-docker-images
    strategy:
      matrix:
        package: ["test-service", "test-runner"]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        with:
          install: true
      - name: Available platforms
        run: echo "${PLATFORMS}"
        env:
          PLATFORMS: ${{ steps.buildx.outputs.platforms }}
      - name: Login to the Container registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          username: nadunrds
          password: ${{ secrets.docker_hub_token }}
      - name: Build & Push Docker Image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            GIT_REVISION=${{ github.sha }}
            PROJECT_PKG="github.com/${{ github.repository }}"
          file: docker/Dockerfile.${{ matrix.package }}
          push: true
          tags: nadunrds/k8s-node-perf-evaluator-${{ matrix.package }}:latest
